// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WmsCore.Data;

#nullable disable

namespace Music_Store_Warehouse_App.Migrations
{
    [DbContext(typeof(WmsCoreContext))]
    [Migration("20251122232017_NIP")]
    partial class NIP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WmsCore.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ContractorId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AddressId");

                    b.HasIndex("ContractorId")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("WmsCore.Models.AtrDefinition", b =>
                {
                    b.Property<int>("AtrDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AtrDefinitionId"));

                    b.Property<int>("AttributeGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AtrDefinitionId");

                    b.HasIndex("AttributeGroupId");

                    b.ToTable("AtrDefinition");
                });

            modelBuilder.Entity("WmsCore.Models.AtrGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AtrGroup");
                });

            modelBuilder.Entity("WmsCore.Models.Attribute", b =>
                {
                    b.Property<int>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttributeId"));

                    b.Property<int>("AtrDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttributeId");

                    b.HasIndex("AtrDefinitionId");

                    b.HasIndex("ItemId");

                    b.ToTable("Attribute");
                });

            modelBuilder.Entity("WmsCore.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("WmsCore.Models.Contractor", b =>
                {
                    b.Property<int>("ContractorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractorId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsContractor")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomer")
                        .HasColumnType("bit");

                    b.Property<string>("NIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ContractorId");

                    b.ToTable("Contractor");
                });

            modelBuilder.Entity("WmsCore.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int?>("ContractorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("DocumentId");

                    b.HasIndex("ContractorId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("WmsCore.Models.DocumentItem", b =>
                {
                    b.Property<int>("DocumentItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentItemId"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentItemId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ItemId");

                    b.ToTable("DocumentItem");
                });

            modelBuilder.Entity("WmsCore.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ContractorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ItemId");

                    b.HasIndex("Acronym")
                        .IsUnique();

                    b.HasIndex("CategoryId");

                    b.HasIndex("ContractorId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("WmsCore.Models.ItemInventory", b =>
                {
                    b.Property<int>("ItemInventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemInventoryId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ItemInventoryId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("ItemInventory");
                });

            modelBuilder.Entity("WmsCore.Models.Address", b =>
                {
                    b.HasOne("WmsCore.Models.Contractor", "Contractor")
                        .WithOne("Address")
                        .HasForeignKey("WmsCore.Models.Address", "ContractorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contractor");
                });

            modelBuilder.Entity("WmsCore.Models.AtrDefinition", b =>
                {
                    b.HasOne("WmsCore.Models.AtrGroup", "AttributeGroup")
                        .WithMany("AtrDefinitions")
                        .HasForeignKey("AttributeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeGroup");
                });

            modelBuilder.Entity("WmsCore.Models.Attribute", b =>
                {
                    b.HasOne("WmsCore.Models.AtrDefinition", "AtrDefinition")
                        .WithMany("Attributes")
                        .HasForeignKey("AtrDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WmsCore.Models.Item", "Item")
                        .WithMany("Attributes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtrDefinition");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WmsCore.Models.Document", b =>
                {
                    b.HasOne("WmsCore.Models.Contractor", "Contractor")
                        .WithMany("Documents")
                        .HasForeignKey("ContractorId");

                    b.Navigation("Contractor");
                });

            modelBuilder.Entity("WmsCore.Models.DocumentItem", b =>
                {
                    b.HasOne("WmsCore.Models.Document", "Document")
                        .WithMany("DocumentItems")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WmsCore.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WmsCore.Models.Item", b =>
                {
                    b.HasOne("WmsCore.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WmsCore.Models.Contractor", null)
                        .WithMany("Items")
                        .HasForeignKey("ContractorId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WmsCore.Models.ItemInventory", b =>
                {
                    b.HasOne("WmsCore.Models.Item", "Item")
                        .WithOne("ItemInventory")
                        .HasForeignKey("WmsCore.Models.ItemInventory", "ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WmsCore.Models.AtrDefinition", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("WmsCore.Models.AtrGroup", b =>
                {
                    b.Navigation("AtrDefinitions");
                });

            modelBuilder.Entity("WmsCore.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WmsCore.Models.Contractor", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Documents");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("WmsCore.Models.Document", b =>
                {
                    b.Navigation("DocumentItems");
                });

            modelBuilder.Entity("WmsCore.Models.Item", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("ItemInventory")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
